name: CI

on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100-preview2-014569'
    - run: dotnet build -c Release
    - run: dotnet pack -c Release -o ${{GITHUB_WORKSPACE}}
          
